### PR TITLE
Automatically generate literal models via codegen 

### PR DESCRIPTION
**Pull request by bruno-f-cruz**
This PR supersedes #64 keeping the high level goal of automatically generating models via codegen

Citing the previous PR:

-----

I should preface this PR by saying that the underlying pattern of these enum-like classes is not ideal and smells a bit like an anti-pattern to me. Mainly because of https://github.com/AllenNeuralDynamics/aind-data-schema/issues/960

Several of the patterns I used for the generators reflect the following discussions:
  - Improving Union methods as described in https://github.com/AllenNeuralDynamics/aind-data-schema/issues/843 and https://github.com/AllenNeuralDynamics/aind-data-schema/discussions/794
  - Improve type hinting (https://github.com/AllenNeuralDynamics/aind-data-schema/issues/843)

----

The following points should be considered in as issues and addressed in future PRs:

  - Generating classes from an endpoint instead of CSV files (this could be a suitable solution for #59  and #51 )
  - Removing the CSV files from the pypi package to prevent bloating

### CODE REVIEW

**Comment by bruno-f-cruz** [comment]
As a reminder, the depended upon library (https://github.com/AllenNeuralDynamics/aind-pydantic-codegen) must be published to pipy prior to the merge. I suggest going through all the use-cases that we may want to contemplate in this PR, iterate the library to address all cases and make a 0.1.0 release of the package to pipy.

**Comment by dbirman** [comment]
> As a reminder, the depended upon library (https://github.com/AllenNeuralDynamics/aind-pydantic-codegen) must be published to pipy prior to the merge. I suggest going through all the use-cases that we may want to contemplate in this PR, iterate the library to address all cases and make a 0.1.0 release of the package to pipy.

I spent some time reviewing this just now and I'm a bit blocked by the use of this library, which seems very cool but also quite complex. Is this code that's coming from other codegen projects and you wanted to put into a general library or are all the features being used here in a way that I'm not understanding?

Basically I'm worried that this is a complex dependency when we're basically just writing the same pattern repeatedly for each row in a dataframe and we could just hard-code it for each model type in a more maintainable/user-friendly way.

**Comment by bruno-f-cruz** [comment]
> I spent some time reviewing this just now and I'm a bit blocked by the use of this library, which seems very cool but also quite complex. Is this code that's coming from other codegen projects and you wanted to put into a general library or are all the features being used here in a way that I'm not understanding?

The library was written to address the cases I came across in this repository. In cases where I saw an easy path to abstract the functionality, I went for it. I think that most of the complexity in the code has to do with trying to infer/deal with cross-references across models. One could ask users to "hard-code" everything instead of passing proper python classes, but if you go down that route I would probably agree with your next statement where the better solution would be to simply write a macro that users can run in their machine.

> Basically I'm worried that this is a complex dependency when we're basically just writing the same pattern repeatedly for each row in a dataframe and we could just hard-code it for each model type in a more maintainable/user-friendly way.

This is a very good point. When you make the decision to add a new dependency you incur in the good things that it brings but also the bad ones. I am by no means claiming that this is the perfect solution and it is likely that there is a more straightforward solution for this single problem that I am not appreciating. 
For what is worth, do not worry about the work that went into it, it was a great experiment and I am sure I will end up using it at some point :P

Thanks for reviewing!

**Comment by bruno-f-cruz** [comment]
> > I think that most of the complexity in the code has to do with trying to infer/deal with cross-references across models.
> 
> Okay this is what I was concerned about -- do you have an example of where this happened? I'm leaning toward using a simplified solution for maintainability, with your permission, but if we need to pull apart cross-references then that could make this backward incompatible.
> 
> Still I think breaking cross-references might be preferred if that allows us to keep the code generator minimal.

I think this happens each time you reference an already existing class. When you enter a seed class, e.g. say your seed is MyClassTemplate, you need, at a bare minimum, import the namespace that has MyClassTemplate. The alternative is to use the strategy I used for the `ForwardClassReference` and rely on the pre-existence of the class (this is necessary in certain cases where you may otherwise have a circular dependency that can't be easily resolved). This strategy reduces code simplicity, but it also puts the effort on the user's side to know where to get all the dependencies from.

The other part of the code that I admit is a bit convoluted is 
https://github.com/AllenNeuralDynamics/aind-pydantic-codegen/blob/13a2e2bf2581db2e6ae8c14752ffd77fdbd9559a/src/aind_pydantic_codegen/generators.py#L574

But I don't think this is unlike the current heuristic that the repo follows here https://github.com/AllenNeuralDynamics/aind-data-schema-models/blob/6a5148c8304bb47356958b80b445469ec5bd83b0/src/aind_data_schema_models/utils.py#L39-L53 with the arbitrary `field_handlers` field which I assumed are callables that can flexible operate on top of the incoming data (not sure, since the type was a dict so I may have missed the point when inferring from the code). I left the parser callables a bit more generic since I suspect that we will want to parsing those that are not from csv documents at some point (e.g. from endpoint requests directly)

Also, are you concerned with the complexity of the code in the library OR the code that I PR'ed  to this repo? If it is an API problem we could potentially address it differently. I guess the relevant file would be this one:
https://github.com/AllenNeuralDynamics/aind-data-schema-models/blob/adf2317987e9dfb4ccd1d767be29a86da6f09f65/src/aind_data_schema_models/_generators/_generate.py

**Comment by dbirman** [comment]
Thanks for the additional detail, I didn't totally follow the first point about dependencies so I think I just need to try to write the macro-based version of this and see where it fails to understand the problem. More on this tomorrow or early next week.

**Comment by bruno-f-cruz** [comment]
> Thanks for the additional detail, I didn't totally follow the first point about dependencies so I think I just need to try to write the macro-based version of this and see where it fails to understand the problem. More on this tomorrow or early next week.

One last note, depending on the complexity of your use-case you can also look into templating tools like [Jinja2](https://jinja.palletsprojects.com/en/stable/). While writing the generator library I wanted to use this instead of all the string interpolation, but never quite got to it. It would replace the `TemplateHelper` interface. If you are looking for an easy and maintainable way to generate the classes text, and, critically, you believe that you wont need a lot of processing to from data source -> generated text, this may be a good way to go about it.

**Comment by dbirman** [comment]
@bruno-f-cruz Jinja2 was a great solution for this. Apologies again for not using the library you built here, hopefully some of this code finds a home in another place. Really appreciate you being supportive of putting together a simplified version of this. 

At the end of the day, we will have functional enum-like classes soon! I can't tag you as a reviewer for some reason but the PR is here https://github.com/AllenNeuralDynamics/aind-data-schema-models/pull/94 and I'd appreciate your input.

**Pull request closed without merging**
